package memoryguard_backend.security.risk;

import memoryguard_backend.security.content.ContentAnalysisResult;
import memoryguard_backend.security.content.ContentSecuritySignal;
import org.springframework.stereotype.Component;

import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;

/**
 * Memory Security Risk Aggregator.
 * <p>
 * Consumes security evidence/signals generated by analysis layers (e.g. Content Analyzer)
 * and transforms them into a structured {@link MemoryRiskAssessment}.
 * <p>
 * Does NOT make policy decisions (ALLOW / REVIEW / BLOCK), adhering strictly to:
 * Detection -> Evidence -> Risk Assessment -> Policy Decision.
 */
@Component
public class MemoryRiskAggregator {

    public MemoryRiskAggregator() {
    }

    /**
     * Aggregates signals from a ContentAnalysisResult into a MemoryRiskAssessment.
     *
     * @param result the content analysis result containing extracted signals
     * @return structured MemoryRiskAssessment
     */
    public MemoryRiskAssessment aggregate(ContentAnalysisResult result) {
        if (result == null || result.getSignals() == null) {
            return aggregate(new ArrayList<ContentSecuritySignal>());
        }
        return aggregate(result.getSignals());
    }

    /**
     * Aggregates a list of ContentSecuritySignal instances into a MemoryRiskAssessment.
     *
     * @param signals list of detected security signals
     * @return structured MemoryRiskAssessment
     */
    public MemoryRiskAssessment aggregate(List<ContentSecuritySignal> signals) {
        if (signals == null || signals.isEmpty()) {
            return new MemoryRiskAssessment(0, "LOW", new ArrayList<>());
        }

        // Defensive copy and filter out null items
        List<ContentSecuritySignal> validSignals = new ArrayList<>();
        for (ContentSecuritySignal sig : signals) {
            if (sig != null) {
                validSignals.add(sig);
            }
        }

        if (validSignals.isEmpty()) {
            return new MemoryRiskAssessment(0, "LOW", new ArrayList<>());
        }

        // Sort signals by severity score descending to prioritize the strongest evidence
        validSignals.sort(Comparator.comparingInt((ContentSecuritySignal s) -> getBaseSeverityScore(s.getSeverity())).reversed());

        List<AggregatedSignalContribution> contributions = new ArrayList<>();
        int totalScore = 0;
        boolean isFirstSignal = true;

        for (ContentSecuritySignal signal : validSignals) {
            int contribution;
            if (isFirstSignal) {
                // Strongest signal provides full base score contribution
                contribution = getBaseSeverityScore(signal.getSeverity());
                isFirstSignal = false;
            } else {
                // Additional signals provide incremental risk boost
                contribution = getIncrementalBoost(signal.getSeverity());
            }

            totalScore += contribution;
            contributions.add(AggregatedSignalContribution.fromContentSignal(signal, contribution));
        }

        int finalScore = Math.min(100, Math.max(0, totalScore));
        String riskLevel = classifyRiskLevel(finalScore);

        return new MemoryRiskAssessment(finalScore, riskLevel, contributions);
    }

    /**
     * Maps severity string to base risk score contribution.
     */
    public int getBaseSeverityScore(String severity) {
        if (severity == null) {
            return 10;
        }
        switch (severity.toUpperCase().trim()) {
            case "CRITICAL":
                return 100;
            case "HIGH":
                return 80;
            case "MEDIUM":
                return 50;
            case "LOW":
                return 20;
            default:
                return 10;
        }
    }

    /**
     * Determines incremental risk boost for additional signals beyond the strongest primary signal.
     */
    private int getIncrementalBoost(String severity) {
        if (severity == null) {
            return 2;
        }
        switch (severity.toUpperCase().trim()) {
            case "CRITICAL":
            case "HIGH":
                return 10;
            case "MEDIUM":
                return 5;
            case "LOW":
                return 2;
            default:
                return 2;
        }
    }

    /**
     * Classifies aggregate risk score into a risk level.
     * <p>
     * 0  - 24 : LOW
     * 25 - 49 : MEDIUM
     * 50 - 74 : HIGH
     * 75 - 100: CRITICAL
     */
    public String classifyRiskLevel(int riskScore) {
        if (riskScore >= 75) {
            return "CRITICAL";
        } else if (riskScore >= 50) {
            return "HIGH";
        } else if (riskScore >= 25) {
            return "MEDIUM";
        } else {
            return "LOW";
        }
    }
}
