package memoryguard_backend.security.content;

import java.util.Objects;

/**
 * Represents a single security signal generated by inspecting memory content.
 */
public class ContentSecuritySignal {

    private String type;
    private String severity;
    private String description;

    public ContentSecuritySignal() {
    }

    public ContentSecuritySignal(String type, String severity, String description) {
        this.type = type;
        this.severity = severity;
        this.description = description;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getSeverity() {
        return severity;
    }

    public void setSeverity(String severity) {
        this.severity = severity;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ContentSecuritySignal signal = (ContentSecuritySignal) o;
        return Objects.equals(type, signal.type) &&
               Objects.equals(severity, signal.severity) &&
               Objects.equals(description, signal.description);
    }

    @Override
    public int hashCode() {
        return Objects.hash(type, severity, description);
    }

    @Override
    public String toString() {
        return "ContentSecuritySignal{" +
                "type='" + type + '\'' +
                ", severity='" + severity + '\'' +
                ", description='" + description + '\'' +
                '}';
    }
}
