package memoryguard_backend.security.content;

import java.util.Objects;

/**
 * Represents a single security signal generated by inspecting memory content.
 */
public class ContentSecuritySignal {

    private String type;
    private String severity;
    private String description;
    private String detector;
    private String evidence;

    public ContentSecuritySignal() {
    }

    public ContentSecuritySignal(String type, String severity, String description) {
        this(type, severity, description, null, null);
    }

    public ContentSecuritySignal(String type, String severity, String description, String detector, String evidence) {
        this.type = type;
        this.severity = severity;
        this.description = description;
        this.detector = detector;
        this.evidence = evidence;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getSeverity() {
        return severity;
    }

    public void setSeverity(String severity) {
        this.severity = severity;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getDetector() {
        return detector;
    }

    public void setDetector(String detector) {
        this.detector = detector;
    }

    public String getEvidence() {
        return evidence;
    }

    public void setEvidence(String evidence) {
        this.evidence = evidence;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        ContentSecuritySignal signal = (ContentSecuritySignal) o;
        return Objects.equals(type, signal.type) &&
               Objects.equals(severity, signal.severity) &&
               Objects.equals(description, signal.description) &&
               Objects.equals(detector, signal.detector) &&
               Objects.equals(evidence, signal.evidence);
    }

    @Override
    public int hashCode() {
        return Objects.hash(type, severity, description, detector, evidence);
    }

    @Override
    public String toString() {
        return "ContentSecuritySignal{" +
                "type='" + type + '\'' +
                ", severity='" + severity + '\'' +
                ", description='" + description + '\'' +
                ", detector='" + detector + '\'' +
                ", evidence='" + evidence + '\'' +
                '}';
    }
}
